### ISSUE TITLE
Set an ARG in Dockerfile for jkroepke/helm-secrets and the associated updatecli manifest

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/docker-helmfile#42]

**Comment by smerle33** [comment]
working on it : https://github.com/jenkins-infra/docker-helmfile/pull/59

**Comment by dduportal** [comment]
Reopening: seems like that #59 fixed #57 .

**Comment by smerle33** [comment]
already done as per https://github.com/jenkins-infra/docker-helmfile/pull/60 #60
